### PR TITLE
v981 Update

### PR DESCRIPTION
**Pull request by d3an**
- Bumped `ib_insync` from 0.9.56 to 0.9.69
- Bumped `IBC` from 3.8.2 to 3.11.0 with relevant config changes
- Bumped `TWS_MAJOR_VRSN` from v978 to v981
- Updated files and configs as necessary

### CODE REVIEW

**Comment by dvasdekis** [comment]
Just noticed you knocked out the v981.3d binary from the repo. 

I know it isn't perfrect, but I think I added it via Github large files support last time - mind if I readd it?

**Comment by dvasdekis** [comment]
I also note that there's a few different timezones used, like Toronto plus also an African timezone in `ib/jts.ini`?

I should probably set the whole thing to UTC for the most repeatability. Does that suit you?

Thanks so much btw! This is great :)

**Comment by d3an** [comment]
> Just noticed you knocked out the v981.3d binary from the repo.
> 
> I know it isn't perfrect, but I think I added it via Github large files support last time - mind if I readd it?

I tried to do it with LFS, but its not supported when dealing with public forks. Basically had to deal with [this](https://github.com/git-lfs/git-lfs/issues/1906). It could probably work for you though.

**Comment by d3an** [comment]
> I also note that there's a few different timezones used, like Toronto plus also an African timezone in `ib/jts.ini`?
> 
> I should probably set the whole thing to UTC for the most repeatability. Does that suit you?
> 
> Thanks so much btw! This is great :)

Yeah, set it all to UTC. Not really sure why the African timezone kept getting repopulated, but still, standardized time zones is a good bet.

**Comment by dnna** [comment]
Nice to see this update! 🙌🎉 Would it be possible to also create a new tag on docker hub with this version?

**Comment by d3an** [comment]
> Nice to see this update! 🙌🎉 Would it be possible to also create a new tag on docker hub with this version?

Sure thing! Hopefully it'll also make the build status badge go green ✅

**Pull request merged**
